name: Generate Image Health Report

on:
  schedule:
    - cron: '30 2 * * 1'  # Runs every monday at 9 AM IST (2:30 AM UTC)
  workflow_dispatch:
    inputs:
      send_mail:
        type: boolean
        description: 'Send email report?'
        required: true
        default: false

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'  # Specify the Python version you need

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies from Pipfile.lock
        run: pipenv install --ignore-pipfile

      - name: Generate Health Report
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          if [ "${{ github.event.inputs.send_mail }}" = "true" ] || [ "${{ github.event_name }}" = "schedule" ]; then
            pipenv run python main.py --send-mail
          else
            pipenv run python main.py
          fi

      - name: Extract HTML report from app.log
        run: |
          # Create the report.html file by extracting HTML content from app.log
          sed -n '/<html/,/<\/html>/p' app.log > report.html

      - name: Upload logs and report as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            app.log
            report.html